desiredState:
  manifest:
    containers:
    - env:
      - name: DB_ROOT_PASSWORD
        value: password
      - name: CEILOMETER_DB_PASSWORD
        value: ceilometerdbpassword
      - name: KEYSTONE_ADMIN_TOKEN
        value: ADMINTOKEN
      image: kollaglue/fedora-rdo-ceilometer-compute
      name: ceilometer-compute
    id: ceilometer-1
    version: v1beta1
id: ceilometer
labels:
  name: ceilometer-compute
